---
# Requires Ansible >= 1.9
- hosts: all
  tasks:
    - name: hello
      shell: echo "hello world"
  roles:
  #- dumpvars
  #- ispmail-packages
  #- ispmail-certificate
  #- ispmail-database
  #- ispmail-postfix
  #- ispmail-dovecot
  #- ispmail-webmail
  #- ispmail-webmail-apache
